### ISSUE TITLE
Crash when multiple lines are entered in "Repo stars"

### ISSUE THREAD

**Issue by PraveenTalari** [pavlospt/refactored-umbrella#7]
**Crash when multiple lines are entered in "Repo stars"**
Log:
22634-22634/com.github.pavlospt.refactoredumbrella E/actoredumbrell: Unknown bits set in runtime_flags: 0x8000
2020-06-02 13:38:11.251 22634-22634/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.pavlospt.refactoredumbrella, PID: 22634
    java.lang.NumberFormatException: For input string: "4
    4"
        at java.lang.Integer.parseInt(Integer.java:615)

**Solution:**
make EditText as single line
and
or make EditText input as number only

**Comment by pavlospt** [comment]
@PraveenTalari Hello! This is a pet project. Its usage is not fine grained and it will not cater for every edge case scenario 😄
